# Keep the normalized app shell and SPA fallback in sync before removing hashed SvelteKit assets.
cp ../public/index.html ../public/200.html;
rm -rf ../public/_app;
rm -f ../public/favicon.svg;
rm -f ../public/index.html.gz ../public/200.html.gz; # deprecated, but may still be generated by older versions of the build process
